package sumapp;

/**
* sumapp/sumaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 30 de julio de 2021 11:07:34 PM COT
*/

public final class sumaHolder implements org.omg.CORBA.portable.Streamable
{
  public sumapp.suma value = null;

  public sumaHolder ()
  {
  }

  public sumaHolder (sumapp.suma initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sumapp.sumaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sumapp.sumaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sumapp.sumaHelper.type ();
  }

}
