package sumapp;


/**
* sumapp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 30 de julio de 2021 11:07:34 PM COT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
